export interface City {
  name: string;
  state: string;
  slug: string;
  intro: string;
  localKeywords: string[];
  serviceAreas: string[];
  areas: string[];  // Alias for centers page
  hasCenter: boolean;
  centerCount: number;
  studentCount: number;
  coordinates: { lat: number; lng: number };
  modes: ('center' | 'home' | 'group' | 'online')[];
  center?: {
    address: string;
    phone: string;
    hours: string;
    mapEmbedUrl: string;
  };
  testimonials: string[];
  faqs: { question: string; answer: string }[];
  popularInstruments: string[];
  metaDescription: string;
}

export const cities: City[] = [
  {
    name: 'Delhi',
    state: 'Delhi',
    slug: 'delhi',
    intro: 'Delhi, the cultural heart of India, has a rich musical heritage spanning Hindustani classical to contemporary genres. SwarShala brings world-class music education to the capital with expert instructors, state-of-the-art facilities, and flexible learning options. Whether you reside in South Delhi, Dwarka, or Rohini, our music programs cater to aspiring musicians of all ages and skill levels.',
    localKeywords: ['music classes in Delhi', 'guitar lessons Delhi', 'piano classes South Delhi', 'vocal training Delhi NCR', 'music academy near me Delhi'],
    serviceAreas: ['South Delhi', 'North Delhi', 'West Delhi', 'East Delhi', 'Dwarka', 'Rohini', 'Vasant Kunj', 'Greater Kailash', 'Hauz Khas', 'Connaught Place', 'Karol Bagh', 'Pitampura'],
    areas: ['Hauz Khas', 'Connaught Place', 'Greater Kailash', 'Dwarka', 'Vasant Kunj'],
    hasCenter: true,
    centerCount: 5,
    studentCount: 2500,
    coordinates: { lat: 28.6139, lng: 77.2090 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: 'A-42, Ground Floor, Hauz Khas Village, New Delhi - 110016',
      phone: '+91-11-4567-8900',
      hours: 'Mon-Sat: 9:00 AM - 8:00 PM, Sun: 10:00 AM - 6:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=hauz+khas+village+delhi&output=embed',
    },
    testimonials: ['testimonial-1', 'testimonial-2', 'testimonial-3'],
    popularInstruments: ['guitar', 'piano', 'vocals', 'tabla', 'violin'],
    faqs: [
      { question: 'Where is SwarShala located in Delhi?', answer: 'Our Delhi center is located in the heart of Hauz Khas Village, easily accessible from South Delhi, Central Delhi, and nearby areas. We also offer home tutor services across Delhi NCR.' },
      { question: 'Do you offer music classes near me in Delhi?', answer: 'Yes! We serve all major areas including South Delhi, Dwarka, Rohini, Vasant Kunj, and more. Choose from center classes, home tutoring, or online sessions.' },
      { question: 'What instruments can I learn at SwarShala Delhi?', answer: 'We offer classes for guitar, piano, keyboard, violin, drums, flute, vocals (Hindustani & Western), tabla, ukulele, and saxophone.' },
      { question: 'What age groups do you teach in Delhi?', answer: 'We welcome students of all ages, from children as young as 5 to adults and seniors. Our curriculum is tailored to each age group.' },
    ],
    metaDescription: 'Premium music classes in Delhi. Learn guitar, piano, vocals, tabla & more at SwarShala Delhi center in Hauz Khas or with home tutors across Delhi NCR. Book a free trial!',
  },
  {
    name: 'Mumbai',
    state: 'Maharashtra',
    slug: 'mumbai',
    intro: 'Mumbai, the entertainment capital of India, thrives on music and performing arts. SwarShala Mumbai brings professional music training to Bollywood\'s home city with experienced faculty from the industry. From Bandra to Andheri, Juhu to Powai, our music programs blend traditional Indian classical with contemporary styles, perfect for Mumbai\'s vibrant artistic community.',
    localKeywords: ['music classes in Mumbai', 'guitar lessons Bandra', 'singing classes Andheri', 'piano teacher Mumbai', 'music school near me Mumbai'],
    serviceAreas: ['Bandra', 'Andheri', 'Juhu', 'Powai', 'Lower Parel', 'Worli', 'Colaba', 'Malad', 'Goregaon', 'Thane', 'Navi Mumbai', 'Borivali'],
    areas: ['Bandra', 'Andheri', 'Juhu', 'Powai', 'Lower Parel'],
    hasCenter: true,
    centerCount: 5,
    studentCount: 2500,
    coordinates: { lat: 19.0760, lng: 72.8777 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '301, Crystal Plaza, Linking Road, Bandra West, Mumbai - 400050',
      phone: '+91-22-4567-8901',
      hours: 'Mon-Sat: 10:00 AM - 9:00 PM, Sun: 11:00 AM - 6:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=linking+road+bandra+mumbai&output=embed',
    },
    testimonials: ['testimonial-4', 'testimonial-5', 'testimonial-6'],
    popularInstruments: ['guitar', 'vocals', 'piano', 'drums', 'keyboard'],
    faqs: [
      { question: 'Where is SwarShala located in Mumbai?', answer: 'Our flagship Mumbai center is on Linking Road, Bandra West. We also provide home tutors across Mumbai, Thane, and Navi Mumbai.' },
      { question: 'Can I learn Bollywood singing at SwarShala Mumbai?', answer: 'Absolutely! Our vocal program includes Bollywood playback, Western vocals, and Hindustani classical. Many of our teachers have industry experience.' },
      { question: 'Do you offer weekend music classes in Mumbai?', answer: 'Yes, we have weekend batches for working professionals and students. Both center classes and home tutoring are available on weekends.' },
      { question: 'What is the fee for music classes in Mumbai?', answer: 'Fees vary by program and instrument. Visit our pricing page or book a free trial to get detailed fee information.' },
    ],
    metaDescription: 'Top music academy in Mumbai. Professional guitar, piano, vocals & drums classes at Bandra center or home tutors across Mumbai. Bollywood-style training available. Free trial!',
  },
  {
    name: 'Bengaluru',
    state: 'Karnataka',
    slug: 'bengaluru',
    intro: 'Bengaluru, India\'s Silicon Valley, is home to a thriving community of tech professionals and music enthusiasts alike. SwarShala Bengaluru caters to this unique blend with flexible scheduling for IT professionals, weekend workshops, and comprehensive music programs. From Koramangala to Whitefield, Indiranagar to HSR Layout, we bring premium music education to the Garden City.',
    localKeywords: ['music classes in Bengaluru', 'guitar classes Koramangala', 'piano lessons Indiranagar', 'music academy Whitefield', 'vocal training Bangalore'],
    serviceAreas: ['Koramangala', 'Indiranagar', 'Whitefield', 'HSR Layout', 'Jayanagar', 'JP Nagar', 'BTM Layout', 'Electronic City', 'Marathahalli', 'Yelahanka', 'Banashankari', 'Malleswaram'],
    areas: ['Koramangala', 'Indiranagar', 'Whitefield', 'HSR Layout', 'Jayanagar'],
    hasCenter: true,
    centerCount: 5,
    studentCount: 2200,
    coordinates: { lat: 12.9716, lng: 77.5946 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '123, 1st Floor, 80 Feet Road, Koramangala 4th Block, Bengaluru - 560034',
      phone: '+91-80-4567-8902',
      hours: 'Mon-Sat: 9:00 AM - 9:00 PM, Sun: 10:00 AM - 6:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=koramangala+80+feet+road+bangalore&output=embed',
    },
    testimonials: ['testimonial-7', 'testimonial-8', 'testimonial-9'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'drums', 'violin'],
    faqs: [
      { question: 'Where is SwarShala in Bengaluru?', answer: 'Our Bengaluru center is located in Koramangala 4th Block on 80 Feet Road. We also offer home tutors across all major tech hubs and residential areas.' },
      { question: 'Do you have evening classes for IT professionals?', answer: 'Yes! We specifically cater to working professionals with evening batches (6 PM - 9 PM) and weekend classes. Online sessions offer even more flexibility.' },
      { question: 'Can I learn Carnatic and Western music both?', answer: 'Absolutely. Our vocal and instrumental programs include both Carnatic and Western traditions. Many students explore both styles.' },
      { question: 'Is there parking at the Koramangala center?', answer: 'Yes, there is dedicated parking space for two-wheelers and limited car parking. Street parking is also available nearby.' },
    ],
    metaDescription: 'Best music classes in Bengaluru. Guitar, piano, vocals, drums at Koramangala center or home tutors across Bangalore. Flexible timing for IT professionals. Free trial!',
  },
  {
    name: 'Hyderabad',
    state: 'Telangana',
    slug: 'hyderabad',
    intro: 'Hyderabad, the City of Pearls, boasts a magnificent musical heritage from classical to Tollywood. SwarShala Hyderabad honors this tradition while embracing modern music education. Our programs serve students across HITEC City, Gachibowli, Jubilee Hills, Banjara Hills, and beyond, blending traditional Indian music with contemporary global styles.',
    localKeywords: ['music classes in Hyderabad', 'guitar lessons Gachibowli', 'piano classes Jubilee Hills', 'singing classes HITEC City', 'music academy near me Hyderabad'],
    serviceAreas: ['HITEC City', 'Gachibowli', 'Jubilee Hills', 'Banjara Hills', 'Madhapur', 'Kondapur', 'Kukatpally', 'Secunderabad', 'Begumpet', 'Ameerpet', 'LB Nagar', 'Miyapur'],
    areas: ['HITEC City', 'Gachibowli', 'Jubilee Hills', 'Banjara Hills', 'Madhapur'],
    hasCenter: true,
    centerCount: 4,
    studentCount: 2000,
    coordinates: { lat: 17.3850, lng: 78.4867 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '45, Road No. 10, Jubilee Hills, Hyderabad - 500033',
      phone: '+91-40-4567-8903',
      hours: 'Mon-Sat: 9:00 AM - 8:00 PM, Sun: 10:00 AM - 5:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=jubilee+hills+road+10+hyderabad&output=embed',
    },
    testimonials: ['testimonial-10', 'testimonial-11'],
    popularInstruments: ['guitar', 'vocals', 'keyboard', 'violin', 'flute'],
    faqs: [
      { question: 'Where is SwarShala in Hyderabad?', answer: 'Our Hyderabad center is in Jubilee Hills, Road No. 10. We also serve HITEC City, Gachibowli, and all other areas through home tutoring and online classes.' },
      { question: 'Do you teach Telugu film music?', answer: 'Yes, our vocal program includes Tollywood/Telugu playback singing alongside classical and Western styles.' },
      { question: 'Are there music classes near HITEC City?', answer: 'Our Jubilee Hills center is a short drive from HITEC City. We also offer home tutors and online classes for tech park professionals.' },
      { question: 'What certifications does SwarShala offer?', answer: 'We offer SwarShala certifications at beginner, intermediate, and advanced levels. We also prepare students for Trinity and ABRSM exams.' },
    ],
    metaDescription: 'Premium music academy in Hyderabad. Guitar, piano, vocals, violin classes at Jubilee Hills center or home tutors across Hyderabad. Tollywood training available. Free trial!',
  },
  {
    name: 'Chennai',
    state: 'Tamil Nadu',
    slug: 'chennai',
    intro: 'Chennai, the cultural capital of South India and home to the December music season, has an unparalleled classical music tradition. SwarShala Chennai embraces this rich heritage while offering diverse musical training. From T. Nagar to Adyar, Anna Nagar to Velachery, we bring expert instruction in both Carnatic and Western music traditions to the city.',
    localKeywords: ['music classes in Chennai', 'Carnatic music lessons Chennai', 'guitar classes T Nagar', 'piano classes Anna Nagar', 'vocal training Chennai'],
    serviceAreas: ['T. Nagar', 'Anna Nagar', 'Adyar', 'Velachery', 'Mylapore', 'Besant Nagar', 'Nungambakkam', 'OMR', 'Porur', 'Tambaram', 'Chromepet', 'ECR'],
    areas: ['T. Nagar', 'Anna Nagar', 'Adyar', 'Velachery', 'Mylapore'],
    hasCenter: true,
    centerCount: 4,
    studentCount: 2000,
    coordinates: { lat: 13.0827, lng: 80.2707 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '67, North Usman Road, T. Nagar, Chennai - 600017',
      phone: '+91-44-4567-8904',
      hours: 'Mon-Sat: 8:00 AM - 8:00 PM, Sun: 9:00 AM - 5:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=north+usman+road+t+nagar+chennai&output=embed',
    },
    testimonials: ['testimonial-12', 'testimonial-13'],
    popularInstruments: ['vocals', 'violin', 'veena', 'keyboard', 'guitar'],
    faqs: [
      { question: 'Does SwarShala Chennai teach Carnatic music?', answer: 'Yes! Chennai being the heart of Carnatic music, we have expert gurus for vocal and instrumental Carnatic training alongside Western music.' },
      { question: 'Where is SwarShala located in Chennai?', answer: 'Our Chennai center is on North Usman Road, T. Nagar - the cultural hub of the city. Home tutors available across Chennai.' },
      { question: 'Do you prepare students for Margazhi season performances?', answer: 'Yes, we offer special intensive programs and workshops leading up to the December music season for serious performers.' },
      { question: 'Can adults learn music at SwarShala Chennai?', answer: 'Absolutely! We have dedicated adult batches with flexible timing. It\'s never too late to start your musical journey.' },
    ],
    metaDescription: 'Best music academy in Chennai. Carnatic vocals, violin, guitar, piano at T. Nagar center or home tutors across Chennai. December season prep available. Free trial!',
  },
  {
    name: 'Kolkata',
    state: 'West Bengal',
    slug: 'kolkata',
    intro: 'Kolkata, the City of Joy and birthplace of countless musical legends, holds music close to its heart. SwarShala Kolkata continues this glorious tradition with programs in Hindustani classical, Rabindra Sangeet, and modern genres. From Park Street to Salt Lake, Ballygunge to New Town, we nurture the next generation of musicians in this culturally rich city.',
    localKeywords: ['music classes in Kolkata', 'guitar lessons Salt Lake', 'piano classes Park Street', 'Rabindra Sangeet training Kolkata', 'tabla classes Kolkata'],
    serviceAreas: ['Park Street', 'Salt Lake', 'Ballygunge', 'New Town', 'Gariahat', 'Tollygunge', 'Howrah', 'Jadavpur', 'Alipore', 'Lake Town', 'Behala', 'Dum Dum'],
    areas: ['Park Street', 'Salt Lake', 'Ballygunge', 'New Town', 'Gariahat'],
    hasCenter: true,
    centerCount: 4,
    studentCount: 1800,
    coordinates: { lat: 22.5726, lng: 88.3639 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '89, Shakespeare Sarani, Park Street Area, Kolkata - 700071',
      phone: '+91-33-4567-8905',
      hours: 'Mon-Sat: 10:00 AM - 8:00 PM, Sun: 11:00 AM - 5:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=shakespeare+sarani+kolkata&output=embed',
    },
    testimonials: ['testimonial-14', 'testimonial-15'],
    popularInstruments: ['vocals', 'tabla', 'guitar', 'keyboard', 'sitar'],
    faqs: [
      { question: 'Does SwarShala teach Rabindra Sangeet?', answer: 'Yes! Kolkata being the birthplace of Rabindra Sangeet, we have specialized programs for Tagore songs alongside other genres.' },
      { question: 'Where is SwarShala in Kolkata?', answer: 'Our Kolkata center is on Shakespeare Sarani near Park Street. We also cover Salt Lake, New Town, and South Kolkata with home tutors.' },
      { question: 'Do you teach Hindustani classical music?', answer: 'Absolutely. Our vocal and tabla programs include comprehensive Hindustani classical training in various gharana styles.' },
      { question: 'Are there music classes for senior citizens in Kolkata?', answer: 'Yes, we welcome learners of all ages including senior citizens. Learning music has no age limit at SwarShala.' },
    ],
    metaDescription: 'Top music academy in Kolkata. Vocals, tabla, guitar, Rabindra Sangeet at Park Street center or home tutors across Kolkata. Hindustani classical training. Free trial!',
  },
  {
    name: 'Pune',
    state: 'Maharashtra',
    slug: 'pune',
    intro: 'Pune, the cultural capital of Maharashtra and a hub for education, has a thriving music scene. SwarShala Pune caters to students, professionals, and retirees with comprehensive music programs. From Koregaon Park to Kothrud, Wakad to Hadapsar, our expert instructors bring quality music education across this dynamic city.',
    localKeywords: ['music classes in Pune', 'guitar lessons Koregaon Park', 'piano classes Kothrud', 'vocal training Pune', 'music academy near me Pune'],
    serviceAreas: ['Koregaon Park', 'Kothrud', 'Wakad', 'Baner', 'Aundh', 'Viman Nagar', 'Hadapsar', 'Hinjewadi', 'Magarpatta', 'Shivaji Nagar', 'Camp', 'Deccan'],
    areas: ['Koregaon Park', 'Kothrud', 'Wakad', 'Baner', 'Aundh'],
    hasCenter: true,
    centerCount: 4,
    studentCount: 1800,
    coordinates: { lat: 18.5204, lng: 73.8567 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '156, Lane 7, Koregaon Park, Pune - 411001',
      phone: '+91-20-4567-8906',
      hours: 'Mon-Sat: 9:00 AM - 8:00 PM, Sun: 10:00 AM - 5:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=koregaon+park+pune&output=embed',
    },
    testimonials: ['testimonial-1', 'testimonial-5'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'drums', 'violin'],
    faqs: [
      { question: 'Where is SwarShala located in Pune?', answer: 'Our Pune center is in the heart of Koregaon Park. We also serve Kothrud, Wakad, Hinjewadi, and other areas with home tutors.' },
      { question: 'Do you have music classes near IT parks in Pune?', answer: 'Yes! We offer evening and weekend batches convenient for IT professionals in Hinjewadi, Magarpatta, and Viman Nagar areas.' },
      { question: 'Can college students afford SwarShala?', answer: 'We offer flexible payment plans and group class discounts. Visit our pricing page or book a trial to learn about student-friendly options.' },
      { question: 'Do you conduct music workshops in Pune?', answer: 'Yes, we regularly organize workshops on various instruments and genres. Follow us for upcoming workshop announcements.' },
    ],
    metaDescription: 'Best music classes in Pune. Guitar, piano, vocals, drums at Koregaon Park center or home tutors across Pune. IT professional batches available. Free trial!',
  },
  {
    name: 'Ahmedabad',
    state: 'Gujarat',
    slug: 'ahmedabad',
    intro: 'Ahmedabad, Gujarat\'s cultural and commercial hub, has a growing appreciation for music education. SwarShala Ahmedabad brings structured, professional music training to the city. From SG Highway to Vastrapur, Satellite to Navrangpura, we cater to students and professionals seeking quality music instruction.',
    localKeywords: ['music classes in Ahmedabad', 'guitar lessons SG Highway', 'piano classes Vastrapur', 'vocal training Ahmedabad', 'music academy Satellite'],
    serviceAreas: ['SG Highway', 'Vastrapur', 'Satellite', 'Navrangpura', 'Paldi', 'Bopal', 'Prahlad Nagar', 'Thaltej', 'Maninagar', 'CG Road', 'Bodakdev', 'Gota'],
    areas: ['SG Highway', 'Vastrapur', 'Satellite', 'Navrangpura', 'Paldi'],
    hasCenter: true,
    centerCount: 3,
    studentCount: 1500,
    coordinates: { lat: 23.0225, lng: 72.5714 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '22, Sakar Complex, SG Highway, Ahmedabad - 380015',
      phone: '+91-79-4567-8907',
      hours: 'Mon-Sat: 9:00 AM - 8:00 PM, Sun: Closed',
      mapEmbedUrl: 'https://maps.google.com/maps?q=sg+highway+ahmedabad&output=embed',
    },
    testimonials: ['testimonial-2', 'testimonial-8'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'harmonium', 'tabla'],
    faqs: [
      { question: 'Where is SwarShala in Ahmedabad?', answer: 'Our Ahmedabad center is on SG Highway, easily accessible from Vastrapur, Satellite, and surrounding areas. Home tutors available city-wide.' },
      { question: 'Do you teach Gujarati folk music?', answer: 'While our primary focus is classical and contemporary music, our vocal program can incorporate regional folk styles upon request.' },
      { question: 'Are there weekend music classes in Ahmedabad?', answer: 'Yes, we have Saturday batches for working professionals and students. The center is closed on Sundays.' },
      { question: 'Can I learn harmonium at SwarShala?', answer: 'Yes! Harmonium is a popular instrument in Gujarat, and we have experienced instructors for harmonium training.' },
    ],
    metaDescription: 'Premium music classes in Ahmedabad. Guitar, piano, vocals, harmonium at SG Highway center or home tutors across Ahmedabad. Weekend batches available. Free trial!',
  },
  {
    name: 'Jaipur',
    state: 'Rajasthan',
    slug: 'jaipur',
    intro: 'Jaipur, the Pink City and a UNESCO World Heritage site, has a royal musical heritage. SwarShala Jaipur brings contemporary music education while honoring traditional arts. From Malviya Nagar to Vaishali Nagar, C-Scheme to Mansarovar, we serve the city with comprehensive music programs.',
    localKeywords: ['music classes in Jaipur', 'guitar lessons Malviya Nagar', 'piano classes C-Scheme', 'vocal training Jaipur', 'music academy near me Jaipur'],
    serviceAreas: ['Malviya Nagar', 'Vaishali Nagar', 'C-Scheme', 'Mansarovar', 'Raja Park', 'Tonk Road', 'Jagatpura', 'Sodala', 'Bani Park', 'MI Road', 'Vidhyadhar Nagar', 'Sitapura'],
    areas: ['Malviya Nagar', 'Vaishali Nagar', 'C-Scheme', 'Mansarovar', 'Raja Park'],
    hasCenter: true,
    centerCount: 3,
    studentCount: 1200,
    coordinates: { lat: 26.9124, lng: 75.7873 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '78, First Floor, Tonk Road, Near Durgapura, Jaipur - 302018',
      phone: '+91-141-456-7890',
      hours: 'Mon-Sat: 9:00 AM - 7:00 PM, Sun: 10:00 AM - 4:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=tonk+road+jaipur&output=embed',
    },
    testimonials: ['testimonial-3', 'testimonial-9'],
    popularInstruments: ['guitar', 'vocals', 'keyboard', 'tabla', 'flute'],
    faqs: [
      { question: 'Where is SwarShala located in Jaipur?', answer: 'Our Jaipur center is on Tonk Road near Durgapura. We cover all major areas including Malviya Nagar and Vaishali Nagar with home tutors.' },
      { question: 'Do you teach Rajasthani folk music?', answer: 'Our programs primarily focus on classical and contemporary styles, but we can recommend specialized folk music teachers upon request.' },
      { question: 'Is there parking at the Jaipur center?', answer: 'Yes, there is parking available at our center for both two-wheelers and cars.' },
      { question: 'Can I learn multiple instruments at SwarShala?', answer: 'Absolutely! Many students learn 2-3 instruments simultaneously. We offer flexible scheduling to accommodate this.' },
    ],
    metaDescription: 'Best music academy in Jaipur. Guitar, vocals, piano, tabla at Tonk Road center or home tutors across Jaipur. All ages welcome. Free trial!',
  },
  {
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    slug: 'lucknow',
    intro: 'Lucknow, the City of Nawabs, has an aristocratic musical tradition with deep roots in Hindustani classical music. SwarShala Lucknow honors this legacy while offering modern music education. From Hazratganj to Gomti Nagar, Aliganj to Indira Nagar, we bring quality music training to the city of tehzeeb.',
    localKeywords: ['music classes in Lucknow', 'guitar lessons Gomti Nagar', 'classical music classes Lucknow', 'vocal training Hazratganj', 'tabla classes Lucknow'],
    serviceAreas: ['Hazratganj', 'Gomti Nagar', 'Aliganj', 'Indira Nagar', 'Mahanagar', 'Alambagh', 'Chinhat', 'Vikas Nagar', 'Jankipuram', 'Rajajipuram', 'Ashiyana', 'Amar Shaheed Path'],
    areas: ['Hazratganj', 'Gomti Nagar', 'Aliganj', 'Indira Nagar', 'Mahanagar'],
    hasCenter: false,
    centerCount: 2,
    studentCount: 800,
    coordinates: { lat: 26.8467, lng: 80.9462 },
    modes: ['home', 'group', 'online'],
    testimonials: ['testimonial-4', 'testimonial-10'],
    popularInstruments: ['vocals', 'tabla', 'guitar', 'harmonium', 'sitar'],
    faqs: [
      { question: 'Does SwarShala have a center in Lucknow?', answer: 'We currently offer home tutor services and online classes in Lucknow. A physical center is coming soon to Gomti Nagar.' },
      { question: 'Can I learn Lucknow gharana classical music?', answer: 'Yes! Our vocal program includes Hindustani classical with teachers trained in various gharana traditions.' },
      { question: 'Which areas in Lucknow do you cover?', answer: 'Our home tutors serve Hazratganj, Gomti Nagar, Aliganj, Indira Nagar, and all major residential areas in Lucknow.' },
      { question: 'Do you teach sitar in Lucknow?', answer: 'Yes, we have experienced sitar teachers available for home tutoring in Lucknow.' },
    ],
    metaDescription: 'Quality music classes in Lucknow. Vocals, tabla, guitar, sitar with home tutors across Lucknow or online. Hindustani classical training. Free trial!',
  },
  {
    name: 'Chandigarh',
    state: 'Chandigarh',
    slug: 'chandigarh',
    intro: 'Chandigarh, the City Beautiful and planned capital of Punjab and Haryana, has a refined cultural scene. SwarShala Chandigarh caters to the discerning residents of this well-organized city with systematic music education programs. From Sector 17 to Sector 35, Mohali to Panchkula, we serve the entire tricity region.',
    localKeywords: ['music classes in Chandigarh', 'guitar lessons Sector 17', 'piano classes Mohali', 'vocal training Chandigarh', 'music academy Panchkula'],
    serviceAreas: ['Sector 17', 'Sector 22', 'Sector 35', 'Sector 43', 'Sector 44', 'Sector 8', 'Sector 9', 'Mohali', 'Panchkula', 'Zirakpur', 'Kharar', 'Industrial Area Phase I'],
    areas: ['Sector 17', 'Sector 22', 'Sector 35', 'Sector 43', 'Sector 44'],
    hasCenter: true,
    centerCount: 3,
    studentCount: 1000,
    coordinates: { lat: 30.7333, lng: 76.7794 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: 'SCO 125, Sector 17-C, Chandigarh - 160017',
      phone: '+91-172-456-7891',
      hours: 'Mon-Sat: 10:00 AM - 7:00 PM, Sun: 11:00 AM - 4:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=sector+17+chandigarh&output=embed',
    },
    testimonials: ['testimonial-5', 'testimonial-11'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'drums', 'flute'],
    faqs: [
      { question: 'Where is SwarShala in Chandigarh?', answer: 'Our Chandigarh center is in Sector 17-C, the main commercial hub. We also serve Mohali, Panchkula, and Zirakpur with home tutors.' },
      { question: 'Do you cover Mohali and Panchkula?', answer: 'Yes! Our home tutors serve the entire Chandigarh tricity including Mohali, Panchkula, and Zirakpur.' },
      { question: 'Are there music classes for children in Chandigarh?', answer: 'Absolutely! We have specially designed programs for children starting from age 5. Our teachers are trained in child-friendly teaching methods.' },
      { question: 'Do you offer group music classes?', answer: 'Yes, we have group classes at our center for guitar, keyboard, and vocals. Group classes are economical and fun!' },
    ],
    metaDescription: 'Top music academy in Chandigarh. Guitar, piano, vocals, drums at Sector 17 center or home tutors in Mohali, Panchkula. Tricity coverage. Free trial!',
  },
  {
    name: 'Kochi',
    state: 'Kerala',
    slug: 'kochi',
    intro: 'Kochi, the Queen of the Arabian Sea, blends traditional Kerala arts with cosmopolitan influences. SwarShala Kochi brings quality music education to this vibrant port city. From Marine Drive to Kakkanad, Edappally to Fort Kochi, we serve aspiring musicians across Ernakulam district with diverse programs.',
    localKeywords: ['music classes in Kochi', 'guitar lessons Kakkanad', 'piano classes Edappally', 'Carnatic music Kochi', 'music academy Ernakulam'],
    serviceAreas: ['Marine Drive', 'Kakkanad', 'Edappally', 'Fort Kochi', 'Panampilly Nagar', 'Kaloor', 'Vytilla', 'Thripunithura', 'Aluva', 'Palarivattom', 'Vyttila', 'Infopark'],
    areas: ['Marine Drive', 'Kakkanad', 'Edappally', 'Fort Kochi', 'Panampilly Nagar'],
    hasCenter: true,
    centerCount: 3,
    studentCount: 1000,
    coordinates: { lat: 9.9312, lng: 76.2673 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: '45, Panampilly Nagar, Near Lulu Mall, Kochi - 682036',
      phone: '+91-484-456-7892',
      hours: 'Mon-Sat: 9:00 AM - 7:00 PM, Sun: 10:00 AM - 4:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=panampilly+nagar+kochi&output=embed',
    },
    testimonials: ['testimonial-6', 'testimonial-12'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'violin', 'veena'],
    faqs: [
      { question: 'Where is SwarShala in Kochi?', answer: 'Our Kochi center is in Panampilly Nagar, near Lulu Mall. We also have home tutors serving Kakkanad, Infopark area, and across Ernakulam.' },
      { question: 'Do you teach Carnatic music in Kochi?', answer: 'Yes! Kerala has a strong Carnatic tradition, and we offer comprehensive Carnatic vocal and instrumental training.' },
      { question: 'Are there music classes near Infopark?', answer: 'We have home tutors serving the Kakkanad-Infopark area, and our Panampilly center is a short drive away.' },
      { question: 'Do you teach Chenda or Kerala percussion?', answer: 'Our primary focus is on mainstream instruments, but we can connect you with specialized traditional percussion teachers.' },
    ],
    metaDescription: 'Best music academy in Kochi. Guitar, piano, Carnatic vocals, violin at Panampilly center or home tutors across Ernakulam. IT hub coverage. Free trial!',
  },
  {
    name: 'Goa',
    state: 'Goa',
    slug: 'goa',
    intro: 'Goa, India\'s sunshine state with Portuguese influences, has a unique musical culture. SwarShala Goa embraces this blend with programs spanning Western classical, contemporary, and Indian genres. From Panaji to Margao, Vasco to Mapusa, we bring professional music education to this musically vibrant state.',
    localKeywords: ['music classes in Goa', 'guitar lessons Panaji', 'piano classes Margao', 'vocal training Goa', 'music academy Panjim'],
    serviceAreas: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda', 'Calangute', 'Candolim', 'Porvorim', 'Dona Paula', 'Bambolim', 'Alto Porvorim', 'Taleigao'],
    areas: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
    hasCenter: false,
    centerCount: 2,
    studentCount: 500,
    coordinates: { lat: 15.2993, lng: 74.1240 },
    modes: ['home', 'group', 'online'],
    testimonials: ['testimonial-7', 'testimonial-13'],
    popularInstruments: ['guitar', 'piano', 'vocals', 'drums', 'ukulele'],
    faqs: [
      { question: 'Does SwarShala have a center in Goa?', answer: 'We currently operate through home tutors and online classes in Goa. Physical center coming soon to Panaji.' },
      { question: 'Can I learn Western classical music in Goa?', answer: 'Absolutely! Given Goa\'s Western heritage, we have strong programs in Western classical guitar, piano, and vocals.' },
      { question: 'Do you have music teachers in South Goa?', answer: 'Yes, our home tutors serve both North Goa (Panaji, Mapusa) and South Goa (Margao, Vasco).' },
      { question: 'Are there seasonal music workshops in Goa?', answer: 'Yes, we organize special workshops during the tourist season. Follow us for announcements.' },
    ],
    metaDescription: 'Quality music classes in Goa. Guitar, piano, vocals, drums with home tutors across Panaji, Margao, Vasco. Western & Indian music. Free trial!',
  },
  {
    name: 'Indore',
    state: 'Madhya Pradesh',
    slug: 'indore',
    intro: 'Indore, the cleanest city in India and commercial capital of Madhya Pradesh, has a growing appreciation for arts education. SwarShala Indore brings systematic music training to this progressive city. From Vijay Nagar to Palasia, Sapna Sangeeta to Rajwada, we serve music enthusiasts across the city.',
    localKeywords: ['music classes in Indore', 'guitar lessons Vijay Nagar', 'piano classes Sapna Sangeeta', 'vocal training Indore', 'music academy Palasia'],
    serviceAreas: ['Vijay Nagar', 'Palasia', 'Sapna Sangeeta', 'Rajwada', 'MG Road', 'Scheme 54', 'Scheme 78', 'AB Road', 'Bhawarkuan', 'Geeta Bhawan', 'South Tukoganj', 'Ring Road'],
    areas: ['Vijay Nagar', 'Palasia', 'Sapna Sangeeta', 'Rajwada', 'MG Road'],
    hasCenter: false,
    centerCount: 2,
    studentCount: 700,
    coordinates: { lat: 22.7196, lng: 75.8577 },
    modes: ['home', 'group', 'online'],
    testimonials: ['testimonial-8', 'testimonial-14'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'harmonium', 'tabla'],
    faqs: [
      { question: 'Does SwarShala have a center in Indore?', answer: 'We currently offer home tutor services and online classes in Indore. A physical center is planned for Vijay Nagar area.' },
      { question: 'Which areas do you cover in Indore?', answer: 'Our home tutors serve all major areas including Vijay Nagar, Palasia, Sapna Sangeeta, and South Tukoganj.' },
      { question: 'Do you teach Malwi folk music?', answer: 'Our primary programs focus on classical and contemporary music, but we can arrange specialized folk music lessons upon request.' },
      { question: 'Are online classes effective?', answer: 'Yes! Our online classes use high-quality video and structured curriculum. Many students prefer the convenience of learning from home.' },
    ],
    metaDescription: 'Quality music classes in Indore. Guitar, keyboard, vocals, tabla with home tutors across Vijay Nagar, Palasia, Sapna Sangeeta. Online classes available. Free trial!',
  },
  {
    name: 'Nagpur',
    state: 'Maharashtra',
    slug: 'nagpur',
    intro: 'Nagpur, the Orange City and geographic center of India, has a burgeoning cultural scene. SwarShala Nagpur brings structured music education to this central Indian city. From Dharampeth to Sadar, Civil Lines to Sitabuldi, we serve aspiring musicians with quality instruction.',
    localKeywords: ['music classes in Nagpur', 'guitar lessons Dharampeth', 'piano classes Sadar', 'vocal training Nagpur', 'music academy Civil Lines'],
    serviceAreas: ['Dharampeth', 'Sadar', 'Civil Lines', 'Sitabuldi', 'Ramdaspeth', 'Wardha Road', 'Manish Nagar', 'Pratap Nagar', 'Trimurti Nagar', 'Laxmi Nagar', 'Hingna', 'IT Park'],
    areas: ['Dharampeth', 'Sadar', 'Civil Lines', 'Sitabuldi', 'Ramdaspeth'],
    hasCenter: false,
    centerCount: 2,
    studentCount: 600,
    coordinates: { lat: 21.1458, lng: 79.0882 },
    modes: ['home', 'group', 'online'],
    testimonials: ['testimonial-9', 'testimonial-15'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'harmonium', 'drums'],
    faqs: [
      { question: 'Does SwarShala have a center in Nagpur?', answer: 'We currently operate through home tutors and online classes in Nagpur. A physical center is in planning for Dharampeth area.' },
      { question: 'Can I learn harmonium in Nagpur?', answer: 'Yes! Harmonium is popular in Central India, and we have experienced harmonium teachers in Nagpur.' },
      { question: 'Do you cover MIHAN/IT Park area?', answer: 'Yes, our home tutors serve MIHAN, Wardha Road, and all major areas of Nagpur.' },
      { question: 'What is the fee structure in Nagpur?', answer: 'Our fees are competitive and vary by program type. Book a free trial to get detailed pricing for your preferred program.' },
    ],
    metaDescription: 'Quality music classes in Nagpur. Guitar, keyboard, vocals, harmonium with home tutors across Dharampeth, Sadar, Civil Lines. Online available. Free trial!',
  },
  {
    name: 'Coimbatore',
    state: 'Tamil Nadu',
    slug: 'coimbatore',
    intro: 'Coimbatore, the Manchester of South India, combines industrial progress with cultural appreciation. SwarShala Coimbatore serves this Tamil Nadu city with comprehensive music programs. From RS Puram to Gandhipuram, Peelamedu to Saibaba Colony, we bring quality music education to Kovai.',
    localKeywords: ['music classes in Coimbatore', 'guitar lessons RS Puram', 'Carnatic music Coimbatore', 'piano classes Peelamedu', 'vocal training Kovai'],
    serviceAreas: ['RS Puram', 'Gandhipuram', 'Peelamedu', 'Saibaba Colony', 'Race Course', 'Hopes College', 'Town Hall', 'Singanallur', 'Ganapathy', 'Vadavalli', 'Saravanampatti', 'TIDEL Park'],
    areas: ['RS Puram', 'Gandhipuram', 'Peelamedu', 'Saibaba Colony', 'Race Course'],
    hasCenter: false,
    centerCount: 2,
    studentCount: 700,
    coordinates: { lat: 11.0168, lng: 76.9558 },
    modes: ['home', 'group', 'online'],
    testimonials: ['testimonial-10', 'testimonial-1'],
    popularInstruments: ['vocals', 'violin', 'keyboard', 'guitar', 'veena'],
    faqs: [
      { question: 'Does SwarShala have a center in Coimbatore?', answer: 'We currently offer home tutor services and online classes in Coimbatore. A physical center is planned for RS Puram area.' },
      { question: 'Do you teach Carnatic music in Coimbatore?', answer: 'Yes! Being in Tamil Nadu, we have strong Carnatic vocal and violin programs alongside Western music.' },
      { question: 'Which areas in Coimbatore do you cover?', answer: 'Our home tutors serve RS Puram, Peelamedu, Saibaba Colony, Race Course, and all major residential areas.' },
      { question: 'Are there music classes near TIDEL Park?', answer: 'Yes, our home tutors serve the Saravanampatti-TIDEL Park area for IT professionals.' },
    ],
    metaDescription: 'Quality music classes in Coimbatore. Carnatic vocals, violin, guitar, keyboard with home tutors across RS Puram, Peelamedu. Online available. Free trial!',
  },
  {
    name: 'Thiruvananthapuram',
    state: 'Kerala',
    slug: 'thiruvananthapuram',
    intro: 'Thiruvananthapuram, the capital of God\'s Own Country, has a rich cultural heritage. SwarShala Trivandrum serves this historic city with quality music education programs. From Technopark to Kowdiar, Vazhuthacaud to Pattom, we bring professional music training to Kerala\'s capital.',
    localKeywords: ['music classes in Trivandrum', 'guitar lessons Technopark', 'Carnatic music Thiruvananthapuram', 'piano classes Kowdiar', 'vocal training Kerala capital'],
    serviceAreas: ['Technopark', 'Kowdiar', 'Vazhuthacaud', 'Pattom', 'Kesavadasapuram', 'Ulloor', 'Kazhakkoottam', 'Sreekaryam', 'Statue', 'Palayam', 'Thampanoor', 'Vellayambalam'],
    areas: ['Technopark', 'Kowdiar', 'Vazhuthacaud', 'Pattom', 'Kesavadasapuram'],
    hasCenter: false,
    centerCount: 2,
    studentCount: 600,
    coordinates: { lat: 8.5241, lng: 76.9366 },
    modes: ['home', 'group', 'online'],
    testimonials: ['testimonial-11', 'testimonial-2'],
    popularInstruments: ['vocals', 'keyboard', 'guitar', 'violin', 'veena'],
    faqs: [
      { question: 'Does SwarShala have a center in Thiruvananthapuram?', answer: 'We currently operate through home tutors and online classes in Trivandrum. A physical center is planned for the city.' },
      { question: 'Do you cover Technopark area?', answer: 'Yes! We have dedicated home tutors serving IT professionals in Technopark and Kazhakkoottam areas.' },
      { question: 'Is Carnatic music training available?', answer: 'Absolutely! Our vocal and instrumental programs include comprehensive Carnatic training with experienced gurus.' },
      { question: 'Do you have Malayalam-speaking teachers?', answer: 'Yes, most of our Trivandrum teachers are fluent in Malayalam and can teach in the local language.' },
    ],
    metaDescription: 'Quality music classes in Thiruvananthapuram. Carnatic vocals, violin, guitar with home tutors across Technopark, Kowdiar. Online available. Free trial!',
  },
  {
    name: 'Noida',
    state: 'Uttar Pradesh',
    slug: 'noida',
    intro: 'Noida, part of the Delhi NCR and a major IT hub, has a young, dynamic population seeking quality music education. SwarShala Noida caters to this modern city with flexible programs. From Sector 18 to Sector 62, Greater Noida to Noida Extension, we serve music enthusiasts across this planned city.',
    localKeywords: ['music classes in Noida', 'guitar lessons Sector 18', 'piano classes Greater Noida', 'vocal training Noida NCR', 'music academy Sector 62'],
    serviceAreas: ['Sector 18', 'Sector 62', 'Sector 15', 'Sector 50', 'Greater Noida', 'Noida Extension', 'Sector 137', 'Sector 128', 'Golf Course', 'Knowledge Park', 'Pari Chowk', 'Expressway'],
    areas: ['Sector 18', 'Sector 62', 'Sector 15', 'Sector 50', 'Greater Noida'],
    hasCenter: true,
    centerCount: 3,
    studentCount: 1500,
    coordinates: { lat: 28.5355, lng: 77.3910 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: 'A-45, Sector 18, Noida - 201301',
      phone: '+91-120-456-7893',
      hours: 'Mon-Sat: 10:00 AM - 8:00 PM, Sun: 11:00 AM - 5:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=sector+18+noida&output=embed',
    },
    testimonials: ['testimonial-12', 'testimonial-3'],
    popularInstruments: ['guitar', 'keyboard', 'vocals', 'drums', 'piano'],
    faqs: [
      { question: 'Where is SwarShala in Noida?', answer: 'Our Noida center is in Sector 18, the main commercial hub. We also serve Greater Noida and Noida Extension with home tutors.' },
      { question: 'Do you have evening classes for IT professionals?', answer: 'Yes! Our Noida center has dedicated evening batches (6 PM - 9 PM) for working professionals.' },
      { question: 'Is Greater Noida covered?', answer: 'Yes, our home tutors serve Greater Noida, Knowledge Park, and Pari Chowk areas. Online classes are also available.' },
      { question: 'What is the metro connectivity to your center?', answer: 'Our Sector 18 center is walking distance from Sector 18 Metro Station on the Aqua Line.' },
    ],
    metaDescription: 'Top music academy in Noida. Guitar, piano, vocals, drums at Sector 18 center or home tutors across Noida, Greater Noida. IT professional batches. Free trial!',
  },
  {
    name: 'Gurugram',
    state: 'Haryana',
    slug: 'gurugram',
    intro: 'Gurugram (Gurgaon), the millennium city and corporate hub of India, has a cosmopolitan population seeking world-class music education. SwarShala Gurugram caters to this premium market with sophisticated music programs. From Golf Course Road to Cyber City, Sohna Road to DLF Phase areas, we serve Gurgaon\'s discerning residents.',
    localKeywords: ['music classes in Gurugram', 'guitar lessons Golf Course Road', 'piano classes DLF', 'vocal training Gurgaon', 'music academy Cyber City'],
    serviceAreas: ['Golf Course Road', 'DLF Phase 1', 'DLF Phase 2', 'DLF Phase 3', 'DLF Phase 4', 'DLF Phase 5', 'Cyber City', 'Sohna Road', 'MG Road', 'Sector 14', 'Sector 29', 'Sushant Lok'],
    areas: ['Golf Course Road', 'DLF Phase 1', 'DLF Phase 2', 'DLF Phase 3', 'DLF Phase 4'],
    hasCenter: true,
    centerCount: 4,
    studentCount: 1800,
    coordinates: { lat: 28.4595, lng: 77.0266 },
    modes: ['center', 'home', 'group', 'online'],
    center: {
      address: 'Tower B, Ground Floor, Golf Course Road, Sector 54, Gurugram - 122011',
      phone: '+91-124-456-7894',
      hours: 'Mon-Sat: 9:00 AM - 9:00 PM, Sun: 10:00 AM - 6:00 PM',
      mapEmbedUrl: 'https://maps.google.com/maps?q=golf+course+road+gurgaon&output=embed',
    },
    testimonials: ['testimonial-13', 'testimonial-4'],
    popularInstruments: ['piano', 'guitar', 'vocals', 'violin', 'drums'],
    faqs: [
      { question: 'Where is SwarShala in Gurugram?', answer: 'Our Gurugram center is on Golf Course Road, Sector 54 - the premium address for music education. Home tutors serve all DLF phases and surrounding areas.' },
      { question: 'Do you have premium piano programs?', answer: 'Yes! We offer classical piano training with ABRSM and Trinity exam preparation. Our Gurugram center has acoustic pianos for practice.' },
      { question: 'Are there corporate tie-ups available?', answer: 'Yes, we partner with companies for employee wellness programs including music classes. Contact us for corporate rates.' },
      { question: 'Do you cover Sohna Road and New Gurgaon?', answer: 'Yes, our home tutors serve Sohna Road, Southern Peripheral Road, and new Gurgaon sectors.' },
    ],
    metaDescription: 'Premium music academy in Gurugram. Piano, guitar, vocals, violin at Golf Course Road center or home tutors across DLF, Cyber City. Corporate programs. Free trial!',
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((city) => city.slug === slug);
}

export function getCitiesWithCenters(): City[] {
  return cities.filter((city) => city.hasCenter);
}

export function getCitiesByState(state: string): City[] {
  return cities.filter((city) => city.state === state);
}

export const cityNames = cities.map((city) => city.name);
export const citySlugs = cities.map((city) => city.slug);
