export interface Instrument {
    name: string;
    slug: string;
    category: 'string' | 'keyboard' | 'percussion' | 'wind' | 'vocal';
    shortDescription: string;
    longDescription: string;
    whoItsFor: string;
    curriculumOutline: {
        level: string;
        topics: string[];
        duration: string;
    }[];
    outcomes: string[];
    levels: ('beginner' | 'intermediate' | 'advanced')[];
    faqs: { question: string; answer: string }[];
    popularCities: string[];
    relatedInstruments: string[];
    imageSlug: string;
    metaDescription: string;
}

export const instruments: Instrument[] = [
    {
        name: 'Guitar',
        slug: 'guitar',
        category: 'string',
        shortDescription: 'Master the world\'s most popular instrument with acoustic and electric guitar training.',
        longDescription: 'The guitar is the world\'s most versatile and popular instrument, perfect for beginners and seasoned musicians alike. At SwarShala, our guitar program covers acoustic guitar, classical guitar, and electric guitar. Whether you want to strum campfire songs, play fingerstyle classics, shred rock solos, or accompany yourself while singing, our comprehensive curriculum has you covered. Our expert instructors guide you through proper technique, music theory, chord progressions, scales, and repertoire building.',
        whoItsFor: 'Guitar is ideal for anyone aged 6 and above who loves music. It\'s perfect for those who want to sing and accompany themselves, aspiring rock/pop musicians, songwriters, and anyone looking for a portable instrument with diverse applications from classical to metal.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Guitar anatomy and care', 'Proper posture and hand position', 'Basic open chords (A, D, E, G, C)', 'Strumming patterns', 'Simple songs and melodies', 'Reading chord charts and tabs', 'Introduction to fingerpicking'],
                duration: '3-6 months',
            },
            {
                level: 'Intermediate',
                topics: ['Barre chords and moveable shapes', 'Advanced strumming and rhythm', 'Pentatonic and major scales', 'Fingerstyle patterns', 'Music theory for guitarists', 'Song arrangement', 'Introduction to improvisation'],
                duration: '6-12 months',
            },
            {
                level: 'Advanced',
                topics: ['Advanced scales and modes', 'Jazz chords and voicings', 'Solo techniques (bends, hammer-ons, pull-offs)', 'Sweep picking and shredding', 'Composition and arrangement', 'Recording and performance skills', 'Style specialization'],
                duration: '12+ months',
            },
        ],
        outcomes: [
            'Play popular songs with confidence',
            'Accompany yourself while singing',
            'Read music notation and tablature',
            'Understand music theory fundamentals',
            'Perform in front of audiences',
            'Create your own arrangements',
            'Jam with other musicians',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'What type of guitar should I start with?', answer: 'Most beginners start with an acoustic guitar as it builds finger strength and doesn\'t require additional equipment. Classical guitars with nylon strings are gentler on fingers. We\'ll help you choose based on your musical goals.' },
            { question: 'How long does it take to play songs?', answer: 'With regular practice, most students can play simple songs within 2-3 months. You\'ll be strumming along to your favorite tunes while continuing to build advanced skills.' },
            { question: 'Do I need to know music theory?', answer: 'Not initially! Our guitar program integrates theory naturally as you learn. You\'ll understand why things work as you progress, making you a more complete musician.' },
            { question: 'Can children learn guitar?', answer: 'Yes! We have guitars sized for children and kid-friendly curriculum. Children as young as 6 can start learning guitar with proper guidance.' },
            { question: 'Electric or acoustic - which is better for beginners?', answer: 'Both work well! Acoustic builds strength, while electric is physically easier to play. Your choice should depend on the style of music you want to play.' },
        ],
        popularCities: ['delhi', 'mumbai', 'bengaluru', 'pune', 'hyderabad'],
        relatedInstruments: ['ukulele', 'bass-guitar'],
        imageSlug: 'guitar',
        metaDescription: 'Learn guitar at SwarShala - acoustic, classical, and electric guitar classes for all levels. Expert instructors, flexible timing. Online and offline classes. Book a free trial!',
    },
    {
        name: 'Piano',
        slug: 'piano',
        category: 'keyboard',
        shortDescription: 'Discover the elegance of classical piano with comprehensive training from basics to performance.',
        longDescription: 'The piano is the foundation of Western music education and one of the most expressive instruments. At SwarShala, our piano program offers comprehensive training in classical piano technique, music theory, sight-reading, and performance. From Bach to Beethoven, from jazz standards to contemporary pieces, our curriculum covers a wide repertoire. We prepare students for international certifications including ABRSM and Trinity examinations while nurturing their artistic expression.',
        whoItsFor: 'Piano is ideal for anyone seeking a solid musical foundation. It\'s perfect for children starting music education, adults rediscovering their passion, aspiring composers, and those pursuing formal music examinations. Piano skills transfer easily to other keyboard instruments and provide excellent theory grounding.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Piano posture and hand position', 'Note reading (treble and bass clef)', 'Basic scales (C, G, D, F major)', 'Simple melodies and coordination', 'Introduction to dynamics', 'Pedal basics', 'First pieces from method books'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['All major and minor scales', 'Arpeggios and chord inversions', 'Sight-reading development', 'Classical repertoire (Baroque, Classical, Romantic)', 'Theory and harmony', 'Pedaling techniques', 'Performance preparation'],
                duration: '1-2 years',
            },
            {
                level: 'Advanced',
                topics: ['Advanced repertoire', 'Interpretation and expression', 'Competition and exam preparation', 'Chamber music and accompaniment', 'Advanced theory and analysis', 'Memorization techniques', 'Stage presence and performance psychology'],
                duration: '2+ years',
            },
        ],
        outcomes: [
            'Read music fluently in both clefs',
            'Play classical repertoire with expression',
            'Pass ABRSM/Trinity examinations',
            'Understand music theory comprehensively',
            'Perform confidently at recitals',
            'Accompany other musicians',
            'Appreciate classical music deeply',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Do I need a piano at home?', answer: 'For serious study, yes. A digital piano with weighted keys is an excellent affordable option. Acoustic pianos are ideal but not mandatory. We can recommend suitable instruments based on your budget.' },
            { question: 'What age is best to start piano?', answer: 'Children can start as young as 4-5 years, though 6-7 is often ideal. Adults of any age can learn piano - it\'s never too late to begin!' },
            { question: 'How long to prepare for ABRSM Grade 1?', answer: 'With regular practice, most students are ready for Grade 1 within 6-12 months of starting. We provide structured preparation for all grade examinations.' },
            { question: 'Is classical piano the only option?', answer: 'No! While our foundation is classical, we also offer jazz piano, contemporary piano, and popular music tracks based on your interests.' },
            { question: 'How much practice is needed?', answer: 'Beginners should aim for 20-30 minutes daily. As you advance, 45-60 minutes or more becomes beneficial. Consistent daily practice is more effective than long irregular sessions.' },
        ],
        popularCities: ['delhi', 'mumbai', 'gurugram', 'bengaluru', 'pune'],
        relatedInstruments: ['keyboard', 'organ'],
        imageSlug: 'piano',
        metaDescription: 'Classical piano lessons at SwarShala. ABRSM & Trinity exam preparation. Expert instructors for all ages and levels. Online and offline classes across India. Book a free trial!',
    },
    {
        name: 'Keyboard',
        slug: 'keyboard',
        category: 'keyboard',
        shortDescription: 'Learn versatile keyboard skills with electronic music production and live performance techniques.',
        longDescription: 'The electronic keyboard is a versatile instrument perfect for exploring various genres and styles. At SwarShala, our keyboard program teaches you to harness the power of modern keyboards with their multiple sounds, rhythms, and features. From Bollywood playback to jazz, from worship music to live band performance, our curriculum covers practical keyboard skills for real-world applications. Learn to create arrangements, use backing tracks, and program sounds.',
        whoItsFor: 'Keyboard is perfect for those who want versatility - play at church, in a band, at functions, or for personal enjoyment. It\'s ideal for students who want quick results, songwriters exploring arrangements, and anyone interested in electronic music production. Great for all ages starting from 6 years.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Keyboard orientation and features', 'Basic fingering and technique', 'Simple melodies and chords', 'Using auto-accompaniment', 'Basic rhythm patterns', 'Popular song arrangements', 'Introduction to keyboard sounds'],
                duration: '3-6 months',
            },
            {
                level: 'Intermediate',
                topics: ['Chord voicings and progressions', 'Lead sheet reading', 'Genre-specific styles (Bollywood, Pop, Rock)', 'Advanced rhythm programming', 'Playing in a band context', 'Basic music production', 'Live performance skills'],
                duration: '6-12 months',
            },
            {
                level: 'Advanced',
                topics: ['Advanced arranging', 'Synthesizer programming', 'MIDI and DAW integration', 'Professional performance techniques', 'Session musician skills', 'Music direction', 'Teaching methodology'],
                duration: '12+ months',
            },
        ],
        outcomes: [
            'Play popular songs quickly',
            'Perform at events and functions',
            'Create backing tracks',
            'Play in a band or worship team',
            'Understand modern music production',
            'Arrange songs professionally',
            'Read lead sheets and chord charts',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'What\'s the difference between keyboard and piano?', answer: 'Keyboards have lighter touch, multiple sounds, and auto-accompaniment features. Piano focuses on classical technique with weighted keys. We recommend keyboard for versatility and piano for classical depth.' },
            { question: 'Which keyboard should I buy?', answer: 'For beginners, a 61-key keyboard with touch sensitivity is sufficient. Brands like Yamaha, Casio, and Roland offer good options. We\'ll guide you based on budget and goals.' },
            { question: 'Can I transition from keyboard to piano?', answer: 'Yes, but it requires adjustment to weighted keys and classical technique. Many students study both instruments. Our teachers help manage the transition.' },
            { question: 'Is keyboard good for Bollywood music?', answer: 'Absolutely! Keyboard is ideal for Bollywood with its variety of Indian instrument sounds and rhythm patterns.' },
            { question: 'Do you teach music production?', answer: 'Yes, our advanced keyboard curriculum includes music production basics using DAWs and MIDI.' },
        ],
        popularCities: ['mumbai', 'delhi', 'bengaluru', 'chennai', 'kolkata'],
        relatedInstruments: ['piano', 'synthesizer'],
        imageSlug: 'keyboard',
        metaDescription: 'Keyboard classes at SwarShala. Learn Bollywood, pop, rock, and worship music. Versatile training for all ages. Online and offline across India. Book a free trial!',
    },
    {
        name: 'Violin',
        slug: 'violin',
        category: 'string',
        shortDescription: 'Master the expressive violin with training in Western classical and Carnatic traditions.',
        longDescription: 'The violin is one of the most expressive and emotionally powerful instruments. At SwarShala, we offer comprehensive violin training in both Western classical and Carnatic traditions. Our program develops proper bowing technique, intonation, and musicality. From Baroque sonatas to Carnatic kritis, from film music to folk melodies, our curriculum covers diverse repertoire while building solid technical foundation.',
        whoItsFor: 'Violin suits dedicated students who appreciate nuanced, expressive music. Ideal for children aged 5+, classical music enthusiasts, those interested in Indian classical music, and anyone drawn to the violin\'s emotional depth. Requires patience and regular practice for best results.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Violin and bow hold', 'Basic posture and positioning', 'Open strings and first position', 'Simple scales and exercises', 'First pieces and melodies', 'Introduction to music reading', 'Basic bowing techniques'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['Position work (1st-3rd position)', 'Major and minor scales', 'Vibrato development', 'Bowing techniques (detaché, legato, staccato)', 'Intermediate repertoire', 'Music theory integration', 'Ensemble playing'],
                duration: '1-2 years',
            },
            {
                level: 'Advanced',
                topics: ['Higher positions (4th-7th)', 'Advanced techniques (spiccato, sautillé)', 'Concerto repertoire', 'Chamber music', 'Carnatic or Western specialization', 'Performance and audition preparation', 'Competition preparation'],
                duration: '2+ years',
            },
        ],
        outcomes: [
            'Play violin with proper technique',
            'Read and interpret violin music',
            'Perform solo and ensemble pieces',
            'Develop refined intonation',
            'Express emotion through playing',
            'Pass graded examinations',
            'Appreciate classical traditions',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'What age can children start violin?', answer: 'Children can start as young as 4-5 with Suzuki method using fractional size violins. Age 6-7 is often ideal for traditional instruction. We assess each child individually.' },
            { question: 'Is violin hard to learn?', answer: 'Violin requires patience due to the learning curve with intonation and bowing. However, with proper instruction and consistent practice, most students make good progress within months.' },
            { question: 'Do you teach Carnatic violin?', answer: 'Yes! We have expert Carnatic violinists on our faculty, especially in South Indian cities. Students can choose Western classical, Carnatic, or explore both.' },
            { question: 'What size violin do I need?', answer: 'We\'ll help you determine the right size. Children use fractional sizes (1/8 to 3/4) while adults typically use full size. Proper sizing is crucial for technique development.' },
            { question: 'How much practice is needed?', answer: 'Beginners should aim for 20-30 minutes daily. Intermediate and advanced students benefit from 45-90 minutes. Quality focused practice is more important than duration.' },
        ],
        popularCities: ['chennai', 'bengaluru', 'mumbai', 'delhi', 'kochi'],
        relatedInstruments: ['viola', 'cello'],
        imageSlug: 'violin',
        metaDescription: 'Violin lessons at SwarShala - Western classical and Carnatic violin training. Expert instruction for all ages. ABRSM preparation. Online and offline. Book a free trial!',
    },
    {
        name: 'Drums',
        slug: 'drums',
        category: 'percussion',
        shortDescription: 'Develop rhythm mastery with drum kit training covering rock, pop, jazz, and fusion styles.',
        longDescription: 'Drums are the heartbeat of modern music, driving bands and creating the groove. At SwarShala, our drum program covers the complete drum kit - snare, bass, toms, hi-hats, and cymbals. Learn proper stick technique, independence, dynamics, and groove across genres including rock, pop, jazz, funk, and fusion. Our curriculum develops both technical proficiency and musicality to make you a complete drummer.',
        whoItsFor: 'Drums suit energetic students with natural rhythm who enjoy being the backbone of music. Ideal for aspiring rock/pop musicians, those who want to play in bands, and anyone who feels the beat. Great stress-reliever too! Suitable for ages 7 and above.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Drum kit orientation', 'Stick grip and technique', 'Basic beats and fills', 'Quarter and eighth note patterns', 'Hand-foot coordination', 'Reading drum notation', 'Playing along to songs'],
                duration: '3-6 months',
            },
            {
                level: 'Intermediate',
                topics: ['Advanced beats and grooves', 'Sixteenth note patterns', 'Syncopation and ghost notes', 'Genre-specific styles (rock, pop, funk)', 'Drum fills and transitions', 'Song arrangement', 'Playing with click track'],
                duration: '6-12 months',
            },
            {
                level: 'Advanced',
                topics: ['Linear drumming', 'Jazz and swing patterns', 'Odd time signatures', 'Polyrhythms and metric modulation', 'Studio drumming', 'Performance and showmanship', 'Band leadership'],
                duration: '12+ months',
            },
        ],
        outcomes: [
            'Play popular rock/pop songs',
            'Maintain solid tempo and groove',
            'Create appropriate drum parts',
            'Read and write drum notation',
            'Play in a band setting',
            'Perform live with confidence',
            'Develop four-way independence',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Do I need a drum kit at home?', answer: 'Ideally yes, but electronic drum kits are apartment-friendly. Practice pads are sufficient for beginners. We can recommend options based on your living situation and budget.' },
            { question: 'Are drums too loud for apartments?', answer: 'Electronic drum kits with mesh heads and headphones are quiet. Many students in apartments use e-kits successfully. Acoustic drums require sound-treated rooms.' },
            { question: 'What age can kids start drums?', answer: 'Children can start as young as 7. Junior drum kits are available for smaller players. We assess readiness individually based on coordination and attention span.' },
            { question: 'How long to play in a band?', answer: 'With regular practice, students can join a band within 6-12 months. We encourage ensemble experience as early as possible.' },
            { question: 'Do you teach Indian percussion too?', answer: 'Our drum program focuses on Western drum kit. For Indian percussion like tabla, we have dedicated programs.' },
        ],
        popularCities: ['mumbai', 'delhi', 'bengaluru', 'pune', 'hyderabad'],
        relatedInstruments: ['cajon', 'percussion'],
        imageSlug: 'drums',
        metaDescription: 'Drum lessons at SwarShala - rock, pop, jazz, and fusion drumming. Expert instruction for all levels. Electronic and acoustic drums. Online and offline. Book a free trial!',
    },
    {
        name: 'Vocals (Western)',
        slug: 'vocals-western',
        category: 'vocal',
        shortDescription: 'Train your voice with Western vocal techniques including pop, rock, jazz, and classical.',
        longDescription: 'Your voice is the most personal and expressive instrument. At SwarShala, our Western vocals program trains you in contemporary and classical vocal techniques. Learn proper breath support, vocal placement, range extension, and stylistic versatility. From pop and rock to jazz and musical theater, our curriculum develops confident, healthy singers who can perform across genres.',
        whoItsFor: 'Western vocals is for anyone who loves to sing in English and Western styles. Perfect for aspiring playback singers, rock/pop vocalists, musical theater enthusiasts, worship leaders, and anyone wanting to improve their singing. All ages welcome from children to adults.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Breath support fundamentals', 'Basic pitch and ear training', 'Vocal warm-ups and exercises', 'Simple songs in comfortable range', 'Introduction to styles', 'Microphone basics', 'Overcoming performance anxiety'],
                duration: '3-6 months',
            },
            {
                level: 'Intermediate',
                topics: ['Range extension', 'Chest voice and head voice', 'Vocal dynamics and expression', 'Genre techniques (pop, rock, R&B)', 'Harmony and background vocals', 'Song interpretation', 'Performance skills'],
                duration: '6-12 months',
            },
            {
                level: 'Advanced',
                topics: ['Advanced techniques (belt, mix, runs)', 'Vocal styling and improvisation', 'Recording studio skills', 'Stage presence and performance', 'Repertoire development', 'Audition preparation', 'Vocal health and maintenance'],
                duration: '12+ months',
            },
        ],
        outcomes: [
            'Sing with proper technique',
            'Extend vocal range significantly',
            'Perform confidently on stage',
            'Record vocals professionally',
            'Harmonize with others',
            'Interpret songs expressively',
            'Maintain vocal health',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Can anyone learn to sing?', answer: 'Yes! While natural ability varies, proper training improves pitch, tone, and range for virtually everyone. Our teachers have transformed many self-described "non-singers" into confident performers.' },
            { question: 'What if I\'m tone deaf?', answer: 'True tone deafness is rare. Most people who think they\'re tone deaf simply haven\'t trained their ear. Our ear training exercises help develop pitch accuracy.' },
            { question: 'Do you prepare for singing competitions?', answer: 'Yes! We offer competition and audition preparation including song selection, arrangement, and performance coaching.' },
            { question: 'Can I learn both Western and Hindustani vocals?', answer: 'Absolutely! Many students explore both traditions. We recommend starting with one style and adding the other once fundamentals are solid.' },
            { question: 'What age is best to start vocal training?', answer: 'Children can start around age 7-8 with age-appropriate material. For serious training, post-puberty (14+) is often ideal as the voice has settled.' },
        ],
        popularCities: ['mumbai', 'delhi', 'bengaluru', 'goa', 'pune'],
        relatedInstruments: ['vocals-hindustani', 'music-production'],
        imageSlug: 'vocals-western',
        metaDescription: 'Western vocal lessons at SwarShala - pop, rock, jazz, musical theater singing. Professional voice training for all ages. Online and offline across India. Book a free trial!',
    },
    {
        name: 'Vocals (Hindustani)',
        slug: 'vocals-hindustani',
        category: 'vocal',
        shortDescription: 'Learn the rich tradition of Hindustani classical vocals with raga, tala, and devotional music.',
        longDescription: 'Hindustani classical vocal music is one of the world\'s most sophisticated musical traditions. At SwarShala, our Hindustani vocals program provides rigorous training in classical techniques including swar, taal, raag, and bandish. Learn from gurus trained in various gharana traditions. Our curriculum covers classical gayaki, semi-classical forms like thumri and ghazal, devotional music, and light classical styles.',
        whoItsFor: 'Hindustani vocals suits those drawn to Indian classical music, devotional singing, ghazals, or light classical forms. Perfect for students seeking deep musical and spiritual development, aspiring classical performers, and anyone wanting to explore India\'s rich musical heritage. All ages welcome.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Swar gyan (note recognition)', 'Basic alankar (exercises)', 'Introduction to taal (rhythm)', 'Simple raags (Yaman, Bhupali)', 'Basic bandish (compositions)', 'Devotional songs (bhajans)', 'Tanpura accompaniment'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['More raags (Bilawal, Khamaj, Kafi)', 'Taal variations', 'Alaap and taan practice', 'Semi-classical forms', 'Light classical songs', 'Harmonium accompaniment basics', 'Stage presentation'],
                duration: '1-2 years',
            },
            {
                level: 'Advanced',
                topics: ['Complex raags', 'Vilambit compositions', 'Advanced taan techniques', 'Thumri, dadra, ghazal', 'Gharana-specific styles', 'Performance and mehfil', 'Teaching methodology'],
                duration: '2+ years',
            },
        ],
        outcomes: [
            'Sing classical bandish correctly',
            'Identify and perform raags',
            'Maintain taal accurately',
            'Perform semi-classical music',
            'Accompany on harmonium',
            'Present at classical forums',
            'Appreciate Indian musical heritage',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Do I need prior musical knowledge?', answer: 'No prior knowledge is needed. Our beginners program starts from scratch with swar recognition and basic exercises.' },
            { question: 'Which gharana do you teach?', answer: 'Our faculty represents various gharanas including Gwalior, Kirana, and Patiala. We match students with teachers based on their interests and voice type.' },
            { question: 'Can I learn just bhajans and light music?', answer: 'Yes! We offer devotional and light classical tracks for students not interested in rigorous classical training. Some classical foundation is still beneficial.' },
            { question: 'How is online classical vocal training effective?', answer: 'Our online classes use high-quality audio to capture nuances. Many aspects of classical training work well online, though periodic in-person sessions enhance learning.' },
            { question: 'Do you prepare for classical music competitions?', answer: 'Yes, we prepare students for competitions and auditions at various levels, from inter-school to prestigious classical festivals.' },
        ],
        popularCities: ['delhi', 'kolkata', 'lucknow', 'mumbai', 'pune'],
        relatedInstruments: ['harmonium', 'tabla', 'vocals-western'],
        imageSlug: 'vocals-hindustani',
        metaDescription: 'Hindustani classical vocal lessons at SwarShala. Raag, taal, bandish, ghazal, bhajan training. Expert gurus. Online and offline across India. Book a free trial!',
    },
    {
        name: 'Tabla',
        slug: 'tabla',
        category: 'percussion',
        shortDescription: 'Learn the intricate art of tabla with North Indian classical percussion training.',
        longDescription: 'The tabla is the soul of Hindustani classical music - a pair of drums that produce an astonishing range of sounds and rhythms. At SwarShala, our tabla program covers traditional taleem (training) in bols, compositions, and improvisation. Learn the intricate finger techniques, memorize classic compositions, and develop the mathematical precision combined with artistic expression that defines great tabla playing.',
        whoItsFor: 'Tabla suits students fascinated by rhythm and Indian classical music. Ideal for Hindustani classical enthusiasts, those wanting to accompany vocalists or instrumentalists, and anyone drawn to the tabla\'s unique sound. Requires patience and dedication to hand technique development.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Tabla positioning and basics', 'Hand techniques (daya and baya)', 'Basic bols (Na, Ta, Tin, Dha, Dhin)', 'Teen taal introduction', 'Simple kaidas and tukdas', 'Theka practice', 'Tuning basics'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['Advanced bols and combinations', 'More taals (Jhaptaal, Ektaal)', 'Kaida development', 'Rela and tukda repertoire', 'Accompaniment basics', 'Tabla solo structure', 'Laykari (rhythm play)'],
                duration: '1-2 years',
            },
            {
                level: 'Advanced',
                topics: ['Complex taals', 'Advanced laykari', 'Gharana-specific compositions', 'Accompaniment mastery', 'Solo performance', 'Improvisation techniques', 'Teaching methodology'],
                duration: '2+ years',
            },
        ],
        outcomes: [
            'Play standard taals correctly',
            'Accompany classical musicians',
            'Perform tabla solo',
            'Understand taal theory deeply',
            'Play traditional compositions',
            'Improvise with laykari',
            'Appreciate tabla gharanas',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Do I need my own tabla?', answer: 'Yes, having your own tabla is essential for practice. We can help you source quality instruments and teach you basic tuning.' },
            { question: 'How long to learn basic accompaniment?', answer: 'With regular practice, students can provide basic accompaniment within 1-2 years. Basic thekas (patterns) come earlier.' },
            { question: 'Which gharana do you teach?', answer: 'Our faculty represents various gharanas including Delhi, Lucknow, and Punjab. We match students with appropriate teachers.' },
            { question: 'Can children learn tabla?', answer: 'Yes! Children as young as 7-8 can start tabla. The instrument builds discipline, memory, and mathematical thinking.' },
            { question: 'Is online tabla learning effective?', answer: 'Online learning works well for tabla, especially with good audio. Visual demonstrations of hand positions are clear via video.' },
        ],
        popularCities: ['delhi', 'kolkata', 'lucknow', 'mumbai', 'varanasi'],
        relatedInstruments: ['pakhawaj', 'cajon'],
        imageSlug: 'tabla',
        metaDescription: 'Tabla lessons at SwarShala - North Indian classical percussion training. Traditional taleem from expert ustads. Online and offline across India. Book a free trial!',
    },
    {
        name: 'Flute',
        slug: 'flute',
        category: 'wind',
        shortDescription: 'Master the Western concert flute or Indian bansuri with comprehensive wind instrument training.',
        longDescription: 'The flute family spans cultures and centuries - from the Western concert flute to the Indian bansuri. At SwarShala, we offer training in both traditions. Learn breath control, embouchure, and finger technique on your chosen flute. Our curriculum develops tone production, articulation, and musical expression across classical and contemporary repertoire.',
        whoItsFor: 'Flute suits students who appreciate wind instruments and melodic expression. The concert flute is ideal for orchestral aspirations and Western classical music. The bansuri appeals to those drawn to Indian classical and meditative music. Suitable for ages 8+ with proper physical development.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Flute assembly and care', 'Embouchure development', 'Breath control basics', 'First notes and simple scales', 'Basic music reading', 'Simple melodies', 'Posture and holding position'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['Extended range development', 'Articulation techniques', 'Major and minor scales', 'Intermediate repertoire', 'Tone quality refinement', 'Music theory application', 'Ensemble playing'],
                duration: '1-2 years',
            },
            {
                level: 'Advanced',
                topics: ['Advanced techniques', 'Classical repertoire', 'Bansuri: raag development', 'Concert flute: exam preparation', 'Performance skills', 'Extended techniques', 'Style specialization'],
                duration: '2+ years',
            },
        ],
        outcomes: [
            'Produce beautiful flute tone',
            'Play scales and arpeggios fluently',
            'Perform solo and ensemble pieces',
            'Read music confidently',
            'Express emotion through playing',
            'Pass graded examinations',
            'Appreciate flute traditions',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Concert flute or bansuri - which should I learn?', answer: 'It depends on your musical interests. Concert flute suits Western classical and orchestral goals. Bansuri is perfect for Indian classical and film music. We help you choose based on your aspirations.' },
            { question: 'What age can children start flute?', answer: 'Concert flute typically suits ages 8-9+ when arm length and finger coverage are sufficient. Younger children can start with fife or recorder. Bansuri can be started younger with appropriate size instruments.' },
            { question: 'Do you provide instruments?', answer: 'Students need their own instruments for practice. We can recommend appropriate flutes based on type and budget. Some center locations have instruments for initial classes.' },
            { question: 'Is flute good for breathing issues?', answer: 'Flute playing can strengthen respiratory muscles and improve breath control. Many wind players report respiratory benefits. However, consult your doctor if you have specific conditions.' },
            { question: 'How long to produce good tone?', answer: 'Basic tone production takes a few weeks to months. Beautiful, consistent tone develops over 1-2 years of dedicated practice.' },
        ],
        popularCities: ['delhi', 'mumbai', 'bengaluru', 'chennai', 'kolkata'],
        relatedInstruments: ['saxophone', 'clarinet'],
        imageSlug: 'flute',
        metaDescription: 'Flute lessons at SwarShala - Western concert flute and Indian bansuri training. Expert instruction for all levels. Online and offline across India. Book a free trial!',
    },
    {
        name: 'Ukulele',
        slug: 'ukulele',
        category: 'string',
        shortDescription: 'Learn the cheerful ukulele - perfect for beginners and casual musicians seeking quick results.',
        longDescription: 'The ukulele is the friendliest instrument for beginners - portable, affordable, and quick to learn. At SwarShala, our ukulele program gets you strumming songs within weeks. Learn chord shapes, strumming patterns, and fingerpicking on this delightful four-string instrument. From Hawaiian classics to pop hits, the ukulele brings joy to players of all ages.',
        whoItsFor: 'Ukulele is perfect for complete beginners, children as young as 5, and anyone wanting a fun, low-pressure musical experience. Ideal for travelers, casual musicians, and those who want to sing and accompany themselves quickly. Also great as a stepping stone to guitar.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Ukulele basics and tuning', 'First chords (C, G, Am, F)', 'Basic strumming patterns', 'Simple songs', 'Chord transitions', 'Singing and playing', 'Reading chord charts'],
                duration: '2-4 months',
            },
            {
                level: 'Intermediate',
                topics: ['More chords and voicings', 'Fingerpicking patterns', 'Barre chords', 'Music theory for ukulele', 'Song arrangement', 'Performance skills', 'Intermediate repertoire'],
                duration: '4-8 months',
            },
            {
                level: 'Advanced',
                topics: ['Advanced fingerstyle', 'Jazz ukulele', 'Solo arrangements', 'Composition', 'Advanced techniques', 'Performance repertoire', 'Teaching others'],
                duration: '8+ months',
            },
        ],
        outcomes: [
            'Play popular songs quickly',
            'Accompany yourself singing',
            'Entertain family and friends',
            'Read chord charts confidently',
            'Transition to guitar if desired',
            'Perform at casual gatherings',
            'Experience the joy of music',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Is ukulele easier than guitar?', answer: 'Yes! Ukulele has only 4 strings (vs 6), softer nylon strings, and simpler chord shapes. Most students play songs within weeks rather than months.' },
            { question: 'What size ukulele should I get?', answer: 'Soprano is the classic, smallest size - great for kids and traditional sound. Concert is slightly larger with fuller tone. Tenor suits larger hands. We\'ll help you choose.' },
            { question: 'Can kids as young as 5 learn ukulele?', answer: 'Absolutely! Ukulele is one of the best first instruments for young children. Small size, soft strings, and quick progress keep kids engaged.' },
            { question: 'Will ukulele skills transfer to guitar?', answer: 'Yes, many chord shapes and strumming patterns transfer. Ukulele is an excellent stepping stone if guitar is your ultimate goal.' },
            { question: 'Is ukulele just for Hawaiian music?', answer: 'Not at all! You can play pop, rock, folk, jazz, and virtually any genre on ukulele. Its cheerful sound adapts surprisingly well to diverse styles.' },
        ],
        popularCities: ['goa', 'mumbai', 'bengaluru', 'pune', 'delhi'],
        relatedInstruments: ['guitar', 'mandolin'],
        imageSlug: 'ukulele',
        metaDescription: 'Ukulele lessons at SwarShala - perfect for beginners and kids. Play songs in weeks! Fun, affordable music education. Online and offline across India. Book a free trial!',
    },
    {
        name: 'Saxophone',
        slug: 'saxophone',
        category: 'wind',
        shortDescription: 'Learn the soulful saxophone with jazz, pop, and classical training for expressive playing.',
        longDescription: 'The saxophone is one of the most expressive and soulful instruments, bridging classical and jazz traditions. At SwarShala, our saxophone program covers proper embouchure, breath control, and finger technique. From smooth jazz to classical études, from Bollywood numbers to pop hits, learn to make the saxophone sing in your style.',
        whoItsFor: 'Saxophone suits students drawn to jazz, R&B, and soulful music. Ideal for older beginners (10+) due to the instrument\'s size and breath requirements. Perfect for those wanting a distinctive voice in bands and ensembles, and anyone captivated by the saxophone\'s emotional range.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Saxophone assembly and care', 'Embouchure development', 'Basic notes and fingerings', 'Breath control', 'Simple scales', 'First melodies', 'Music reading basics'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['Extended range', 'Major and minor scales', 'Articulation techniques', 'Jazz fundamentals', 'Intermediate repertoire', 'Playing with backing tracks', 'Ensemble skills'],
                duration: '1-2 years',
            },
            {
                level: 'Advanced',
                topics: ['Jazz improvisation', 'Advanced scales and modes', 'Classical repertoire', 'Extended techniques', 'Performance and recording', 'Band leadership', 'Style development'],
                duration: '2+ years',
            },
        ],
        outcomes: [
            'Produce beautiful saxophone tone',
            'Play jazz standards',
            'Improvise confidently',
            'Read music fluently',
            'Perform solo and with bands',
            'Understand jazz harmony',
            'Express emotion through playing',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Alto or tenor - which saxophone should I start with?', answer: 'Alto saxophone is recommended for beginners due to its smaller size and easier key layout. Tenor can be started if you have larger hands and prefer its deeper sound.' },
            { question: 'Is saxophone hard to learn?', answer: 'Saxophone is actually one of the more accessible wind instruments. Basic notes come quickly, though mastering tone and jazz improvisation takes years.' },
            { question: 'What age can children start saxophone?', answer: 'Around age 10-11 is typical when children have sufficient hand size and breath capacity. Some start earlier with proper guidance.' },
            { question: 'Do I need to read music?', answer: 'While many jazz saxophonists play by ear, learning to read music greatly accelerates progress and opens up more repertoire. We teach both skills.' },
            { question: 'Can I play Bollywood songs on saxophone?', answer: 'Absolutely! Saxophone features prominently in Bollywood music. Our repertoire includes popular film songs alongside jazz and classical.' },
        ],
        popularCities: ['mumbai', 'delhi', 'goa', 'bengaluru', 'kolkata'],
        relatedInstruments: ['clarinet', 'flute'],
        imageSlug: 'saxophone',
        metaDescription: 'Saxophone lessons at SwarShala - jazz, pop, classical, and Bollywood saxophone training. Expert instruction for all levels. Online and offline. Book a free trial!',
    },
    {
        name: 'Harmonium',
        slug: 'harmonium',
        category: 'keyboard',
        shortDescription: 'Master the harmonium for Indian classical, devotional, and light music accompaniment.',
        longDescription: 'The harmonium is central to Indian music - essential for accompanying classical vocals, bhajans, kirtans, and ghazals. At SwarShala, our harmonium program teaches proper bellows technique, finger patterns, and accompaniment skills. Learn to support singers, play independently, and understand Indian music theory through this versatile pump organ.',
        whoItsFor: 'Harmonium is ideal for those interested in Indian classical, devotional, or light music. Perfect for aspiring accompanists, bhajan and kirtan enthusiasts, Hindustani vocal students wanting self-accompaniment, and anyone drawn to Indian musical traditions. All ages welcome.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Harmonium basics and bellows', 'Hand positioning', 'Basic swaras and scales', 'Simple bhajans and songs', 'Coordination of hands and bellows', 'Basic music theory', 'First compositions'],
                duration: '4-8 months',
            },
            {
                level: 'Intermediate',
                topics: ['Raag introduction', 'Accompaniment techniques', 'Lehera patterns', 'Semi-classical songs', 'Taal awareness', 'Song arrangement', 'Performance skills'],
                duration: '8-18 months',
            },
            {
                level: 'Advanced',
                topics: ['Advanced raags', 'Classical accompaniment', 'Solo playing', 'Ghazal and thumri accompaniment', 'Teaching methodology', 'Performance repertoire', 'Style refinement'],
                duration: '18+ months',
            },
        ],
        outcomes: [
            'Accompany vocalists confidently',
            'Play bhajans and devotional music',
            'Understand Indian music theory',
            'Perform at religious gatherings',
            'Support classical singers',
            'Play independently',
            'Teach basic harmonium',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Is harmonium good for beginners?', answer: 'Yes! Harmonium is relatively easy to start with fixed pitches unlike stringed instruments. It\'s an excellent entry point to Indian music.' },
            { question: 'Can I use harmonium for Hindustani vocal practice?', answer: 'Absolutely! Many Hindustani vocalists accompany themselves on harmonium for practice and performance. It\'s an essential skill for serious classical students.' },
            { question: 'What type of harmonium should I buy?', answer: 'A 3.25 octave double-reed harmonium is standard for most purposes. We\'ll advise on brands and features based on your needs and budget.' },
            { question: 'Is online harmonium learning effective?', answer: 'Yes, harmonium translates well to online learning. Visual demonstration of fingering and bellows technique works effectively via video.' },
            { question: 'How long to accompany bhajans?', answer: 'With regular practice, students can accompany simple bhajans within 3-6 months. More complex accompaniment develops over 1-2 years.' },
        ],
        popularCities: ['delhi', 'lucknow', 'kolkata', 'ahmedabad', 'mumbai'],
        relatedInstruments: ['keyboard', 'organ'],
        imageSlug: 'harmonium',
        metaDescription: 'Harmonium lessons at SwarShala - Indian classical accompaniment, bhajan, and devotional music training. Expert instruction. Online and offline. Book a free trial!',
    },
    {
        name: 'Veena',
        slug: 'veena',
        category: 'string',
        shortDescription: 'Learn the ancient veena - the queen of South Indian classical instruments.',
        longDescription: 'The veena (Saraswati veena) is the queen of Carnatic music instruments, with origins dating back millennia. At SwarShala, our veena program provides traditional training in this majestic instrument. Learn proper posture, finger techniques, gamaka (ornaments), and classical repertoire. Develop the patience and dedication this divine instrument demands.',
        whoItsFor: 'Veena suits students deeply interested in South Indian classical music and willing to commit to traditional learning. Ideal for those seeking meditative, spiritual musical practice, Carnatic music enthusiasts, and anyone drawn to this ancient, revered instrument. Typically ages 8+ with proper instrument sizing.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Veena positioning and basics', 'Right and left hand techniques', 'Basic swaras and exercises', 'Simple ragas (Mayamalavagowla)', 'Sarali varisai, janta', 'Tuning and care', 'Basic gamakas'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['More ragas and kritis', 'Advanced gamakas', 'Alankaras and geethams', 'Varnam development', 'Kalpana swaram basics', 'Performance preparation', 'Theory integration'],
                duration: '1-3 years',
            },
            {
                level: 'Advanced',
                topics: ['Advanced repertoire', 'Concert kritis', 'Ragam tanam pallavi', 'Manodharma sangeetam', 'Accompaniment skills', 'Performance mastery', 'Teaching methodology'],
                duration: '3+ years',
            },
        ],
        outcomes: [
            'Play classical Carnatic repertoire',
            'Execute gamakas authentically',
            'Perform varnams and kritis',
            'Understand Carnatic theory',
            'Accompany vocalists',
            'Present at classical forums',
            'Appreciate veena tradition',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Is veena difficult to learn?', answer: 'Veena requires dedication and patience due to the complexity of gamakas and left-hand techniques. However, with proper guidance and practice, students make steady progress.' },
            { question: 'Do I need to buy a veena?', answer: 'Yes, owning a veena is essential for practice. We can connect you with reputable instrument makers for quality instruments in various price ranges.' },
            { question: 'What age can children start veena?', answer: 'Children can start around age 8-10 when they can handle the instrument\'s size. Smaller instruments are available for younger students.' },
            { question: 'Is online veena learning possible?', answer: 'Yes, with high-quality video and audio. While in-person guidance has benefits, many students successfully learn veena online with dedicated practice.' },
            { question: 'How long to play a basic kriti?', answer: 'With consistent practice, students typically play simple kritis within 1-2 years. Mastering concert-level pieces takes considerably longer.' },
        ],
        popularCities: ['chennai', 'bengaluru', 'hyderabad', 'kochi', 'coimbatore'],
        relatedInstruments: ['sitar', 'violin'],
        imageSlug: 'veena',
        metaDescription: 'Veena (Saraswati veena) lessons at SwarShala - Carnatic classical training from expert gurus. Traditional South Indian music education. Online and offline. Book a free trial!',
    },
    {
        name: 'Sitar',
        slug: 'sitar',
        category: 'string',
        shortDescription: 'Master the sitar - the iconic stringed instrument of Hindustani classical music.',
        longDescription: 'The sitar is the most recognized Indian classical instrument worldwide, known for its hypnotic sound and meditative qualities. At SwarShala, our sitar program provides traditional training in technique, raag exploration, and improvisational skills. Learn from teachers trained in gharana traditions and discover the depth of this magnificent instrument.',
        whoItsFor: 'Sitar appeals to those fascinated by North Indian classical music and willing to undertake serious study. Perfect for meditation and mindfulness seekers, world music enthusiasts, and anyone captivated by the sitar\'s unique sound. Typically ages 10+ due to the instrument\'s physical demands.',
        curriculumOutline: [
            {
                level: 'Beginner',
                topics: ['Sitar positioning and basics', 'Right hand (mizrab) technique', 'Left hand (meend) basics', 'Basic scales and exercises', 'Simple raags (Yaman, Bhupali)', 'Tuning and maintenance', 'Elementary compositions'],
                duration: '6-12 months',
            },
            {
                level: 'Intermediate',
                topics: ['More raags and bandishes', 'Advanced meend and gamak', 'Alap development', 'Jhala technique', 'Accompaniment awareness', 'Performance structure', 'Gharana introduction'],
                duration: '1-3 years',
            },
            {
                level: 'Advanced',
                topics: ['Complex raags', 'Extended alap and jod', 'Advanced jhala', 'Gharana specialization', 'Concert performance', 'Improvisation mastery', 'Teaching methodology'],
                duration: '3+ years',
            },
        ],
        outcomes: [
            'Play classical raags correctly',
            'Execute meend and gamak',
            'Perform alap, jod, jhala',
            'Understand Hindustani theory',
            'Present at classical venues',
            'Appreciate gharana traditions',
            'Experience meditative depth',
        ],
        levels: ['beginner', 'intermediate', 'advanced'],
        faqs: [
            { question: 'Is sitar very difficult to learn?', answer: 'Sitar has a steep learning curve due to the complexity of meend (slides) and the physical demands. However, dedicated students find it deeply rewarding.' },
            { question: 'Where can I buy a sitar?', answer: 'We can connect you with reputable sitar makers in Kolkata, Delhi, and other cities. Quality is crucial for playability and sound.' },
            { question: 'What age is appropriate to start sitar?', answer: 'Age 10-12 is typically ideal when physical size and finger strength are sufficient. Some start younger with modified instruments.' },
            { question: 'How much practice time is needed?', answer: 'Serious sitar students typically practice 1-2 hours daily. Even 30-45 minutes of focused daily practice yields progress.' },
            { question: 'Can I learn sitar online?', answer: 'Yes, though in-person guidance is valuable, especially initially. Many aspects of sitar training work well via video.' },
        ],
        popularCities: ['delhi', 'kolkata', 'varanasi', 'mumbai', 'lucknow'],
        relatedInstruments: ['veena', 'guitar'],
        imageSlug: 'sitar',
        metaDescription: 'Sitar lessons at SwarShala - Hindustani classical training from expert ustads. Traditional North Indian music education. Online and offline. Book a free trial!',
    },
];

export function getInstrumentBySlug(slug: string): Instrument | undefined {
    return instruments.find((instrument) => instrument.slug === slug);
}

export function getInstrumentsByCategory(category: Instrument['category']): Instrument[] {
    return instruments.filter((instrument) => instrument.category === category);
}

export const instrumentNames = instruments.map((instrument) => instrument.name);
export const instrumentSlugs = instruments.map((instrument) => instrument.slug);
